### ISSUE TITLE
error: unrecognized arguments:

### ISSUE THREAD

**Issue by zabido** [Scarygami/location-history-json-converter#10]
Hi,

based on the readme I cannot figure out how to provide the input file.
My file name is 

> LocationHistory.json

The command I execute:
`python location_history_json_converter.py LocationHistory.json`
The output I get:
`usage: location_history_json_converter.py [-h] [-o OUTPUT]
                                          [-f {kml,json,csv,js,gpx,gpxtracks}]
                                          [-v VARIABLE] [-s STARTDATE]
                                          [-e ENDDATE] [-c]
                                          input
location_history_json_converter.py: error: unrecognized arguments: LocationHisto
ry.json`

I have tried several ways to open it. I typed input in front of the file, input and filename without space. Nothing seems to work for me.
Can you please give a hint how this should be executed to parse the input file?

**Comment by zabido** [comment]
I have found the answer.
If you pass sys.argv to parse_args, then the path or name of the script itself is the first item in sys.argv and thus becomes the value of option.filename. The hehe then becomes an unknown argument.

If you omit sys.argv then parse_args parses sys.argv as expected.

**Comment by jascination** [comment]
@zabido Can you give a clear example here? It seems you're saying that instead of 

     python location_history_json_converter.py LocationHistory.json -f json -o test.json

(which gives `error: unrecognized arguments: LocationHistory.json` ), we should do:

     ./location_history_json_converter.py LocationHistory.json -f json -o test.json

This gives the same error though. What am I missing here?

**Comment by jascination** [comment]
Update: I got this working by changing line 50 to:

    args = arg_parser.parse_args(sys.argv[1:])

**Comment by zabido** [comment]
Hi! Thanks for the feedback!
That should solve it. The problem was that 
`args = arg_parser.parse_args(sys.argv)`
was using the 'location_history_json_converter.py' command as first argument therefore the file name was not passed.
To me it worked like this:
`args = arg_parser.parse_args()`

But I'm sure your solution will work too.

**Comment by gt7599a** [comment]
Has either of these changes been committed?  I tried modifying the .py file to reflect either one of these changes and was still getting the same error as the OP.
